# Arquivo: render.yaml
# Versão: FINAL E COMPLETA - Com movimentação de arquivos de build

services:
  - type: web
    name: modelfleuriet
    region: oregon
    plan: free
    env: python
    rootDir: ./backend
    buildCommand: |
      pip install -r requirements.txt && \
      npm install --prefix ../ && \
      npm run build --prefix ../ && \
      mkdir -p ./public && \
      mv ../dist/* ./public/
    startCommand: "gunicorn flask_app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: '3.10.13'
      - key: DATABASE_URL
        fromDatabase:
          name: modelfleuriet-db
          property: connectionString

databases:
  - name: modelfleuriet-db
    plan: free
