services:
  - type: web
    name: modelfleuriet
    env: python
    region: sao
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p data templates
      cp data/* data/ 2>/dev/null || true
      cp templates/* templates/ 2>/dev/null || true
    startCommand: gunicorn flask_app:app
    envVars:
      - key: DB_USER
        value: seu_usuario
      - key: DB_PASSWORD
        value: sua_senha
      - key: DB_HOST
        value: seu_host
      - key: DB_NAME
        value: seu_banco
      - key: SECRET_KEY
        value: sua_chave_secreta
