# Arquivo: render.yaml

services:
  - type: web
    name: modelfleuriet
    region: oregon
    plan: free
    env: python
    rootDir: .
    # Comando de build corrigido: uma única linha que executa todos os passos em sequência.
    buildCommand: "pip install -r requirements.txt && cd frontend && npm install && npm run build"
    # Comando para iniciar o servidor após o build ser concluído com sucesso.
    startCommand: "gunicorn flask_app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: '3.10.13'
      - key: DATABASE_URL
        fromDatabase:
          name: modelfleuriet-db # Verifique se este é o nome correto do seu DB na Render
          property: connectionString

databases:
  - name: modelfleuriet-db
    plan: free
