# Arquivo: render.yaml
# Versão: FINAL - Para estrutura com Backend e Frontend separados

services:
  - type: web
    name: modelfleuriet
    region: oregon
    plan: free
    env: python
    # O serviço agora roda a partir da pasta 'backend'
    rootDir: ./backend
    # Comandos de build atualizados para a nova estrutura
    buildCommand: "pip install -r requirements.txt && npm install --prefix ../ && npm run build --prefix ../"
    # O comando de start continua o mesmo, pois já estamos dentro da pasta 'backend'
    startCommand: "gunicorn flask_app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: '3.10.13'
      - key: DATABASE_URL
        fromDatabase:
          name: modelfleuriet-db
          property: connectionString

databases:
  - name: modelfleuriet-db
    plan: free
