# Este é um Blueprint da Render. Ele define apenas o serviço web.

services:
  # Define o Serviço Web
  - type: web
    name: modelfleuriet
    region: oregon # CRÍTICO: Mesma região do banco de dados
    env: python
    plan: free # Mude para um plano pago em produção, se necessário
    
    # Filtro de build: só faz novo deploy se arquivos relevantes forem alterados
    buildFilter:
      paths:
      - "flask_app.py"
      - "core/**"
      - "templates/**"
      - "requirements.txt"
      
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn flask_app:app"
    
    # Variáveis de Ambiente: A forma moderna e segura
    envVars:
      # Injeta automaticamente a URL de conexão INTERNA do banco de dados existente.
      - key: DATABASE_URL
        fromDatabase:
          name: modelfleuriet-db # <-- Refere-se ao seu banco de dados já existente
          property: connectionString # <-- CORREÇÃO: A propriedade correta é "connectionString"
          
      # Deixa a Render gerar e gerenciar uma chave secreta segura para você.
      - key: SECRET_KEY
        generateValue: true
        
      - key: PYTHON_VERSION
        value: "3.10.13"
