# Arquivo: render.yaml
# Versão: COMPLETA E ATUALIZADA
# Correção: Utiliza o comando 'npm --prefix' que é mais robusto que 'cd' para
# executar os scripts de frontend no diretório correto.

services:
  - type: web
    name: modelfleuriet
    region: oregon
    plan: free
    env: python
    rootDir: .
    # Comando de build final, usando --prefix:
    buildCommand: "pip install -r requirements.txt && npm install --prefix frontend && npm run build --prefix frontend"
    # Comando para iniciar o servidor após o build ser bem-sucedido:
    startCommand: "gunicorn flask_app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: '3.10.13'
      - key: DATABASE_URL
        fromDatabase:
          name: modelfleuriet-db # Garanta que este nome bate com o do seu DB no Render
          property: connectionString

databases:
  - name: modelfleuriet-db
    plan: free
