services:
  - type: web
    name: modelfleuriet
    env: python
    region: sao
    buildCommand: |
      # Instalar dependências
      pip install -r requirements.txt
      
      # Criar estrutura de diretórios
      mkdir -p core data templates
      
      # Copiar apenas arquivos essenciais
      cp flask_app.py .env Procfile requirements.txt runtime.txt .
      cp core/analysis.py core/
      cp data/* data/
      cp templates/* templates/
    startCommand: gunicorn flask_app:app
    envVars:
      - key: DB_USER
        value: seu_usuario
      - key: DB_PASSWORD
        value: sua_senha
      - key: DB_HOST
        value: seu_host
      - key: DB_NAME
        value: seu_banco
      - key: SECRET_KEY
        value: sua_chave_secreta
    ignorePaths:
      - /dfp_cia_aberta_*.zip
      - /.git
      - /.gitignore
      - /preprocess_to_db_light.py
      - /render.yaml  # O próprio arquivo já está sendo copiado explicitamente
