# Este é um Blueprint da Render. Ele define o serviço web e um job para popular o banco de dados.

services:
  # Define o Serviço Web principal
  - type: web
    name: modelfleuriet
    region: oregon
    env: python
    plan: free
    buildFilter:
      paths:
      - "flask_app.py"
      - "core/**"
      - "templates/**"
      - "requirements.txt"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn flask_app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: modelfleuriet-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.10.13"

  # Define um Job para popular o banco de dados
  # Este job só roda quando você o aciona manualmente.
  - type: job
    name: db-populator
    region: oregon
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python preprocess_to_db_light.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: modelfleuriet-db
          property: connectionString
