# Arquivo: render.yaml
# Versão: DIAGNÓSTICO AVANÇADO
# Objetivo: Listar todos os arquivos no servidor para verificar se
# o 'src/main.jsx' realmente existe antes do build.

services:
  - type: web
    name: modelfleuriet
    region: oregon
    plan: free
    env: python
    rootDir: .
    # Comando de build com diagnóstico:
    buildCommand: "pip install -r requirements.txt && npm install && echo '---[ INICIANDO LISTAGEM DE ARQUIVOS ]---' && ls -lR && echo '---[ FIM DA LISTAGEM, INICIANDO BUILD ]---' && npm run build"
    # Comando para iniciar o servidor:
    startCommand: "gunicorn flask_app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: '3.10.13'
      - key: DATABASE_URL
        fromDatabase:
          name: modelfleuriet-db
          property: connectionString

databases:
  - name: modelfleuriet-db
    plan: free
