services:
  - type: web
    name: modelfleuriet
    region: oregon
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn flask_app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: modelfleuriet-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.10.13"

jobs:
  - name: run-valuation
    type: script
    schedule: "0 3 * * *"  # Executa diariamente às 3h
    script: |
      python run_valuation_worker.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: modelfleuriet-db
          property: connectionString
