services:
  - type: web
    name: modelfleuriet
    region: oregon
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -c "from core.valuation_analysis import VALUATION_CONFIG; print('Configuração de valuation:', VALUATION_CONFIG)"
    startCommand: "gunicorn flask_app:app"
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: PYTHON_VERSION
        value: "3.10.13"
      - key: SECRET_KEY
        value: ${SECRET_KEY}

jobs:
  - name: run-valuation
    type: cron
    schedule: "0 3 * * *"  # 3h UTC (00h BRT)
    plan: free
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
    buildCommand: pip install -r requirements.txt
    runCommand: python run_valuation_worker.py
