# 📍 Caminho: modelfleuriet/render.yaml
# ✅ VERSÃO FINAL SIMPLIFICADA E CORRETA PARA O SEU AMBIENTE

services:
  - type: web
    name: modelfleuriet
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn flask_app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: modelfleuriet-db
          property: connectionString
