services:
  - type: web
    name: modelfleuriet
    region: oregon
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn flask_app:app"
    postDeployCommand: "python preprocess_to_db_light.py"  # 👈 Executa após o deploy
    resources:
      memory: 512MB
      swap: 1GB
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: modelfleuriet-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.10.13"
      - key: SECRET_KEY
        generateValue: true  # Gera automaticamente se necessário

jobs:
  - name: run-valuation
    type: cron
    schedule: "0 3 * * *"  # 3h UTC (00h BRT)
    plan: free
    resources:
      memory: 512MB
      swap: 1GB
    command: "python run_valuation_worker.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: modelfleuriet-db
          property: connectionString
