services:
  - type: web
    name: modelfleuriet
    env: python
    region: sao # Região de São Paulo
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_app:app
    envVars:
      - key: DB_USER
        value: seu_usuario
      - key: DB_PASSWORD
        value: sua_senha
      - key: DB_HOST
        value: seu_host
      - key: DB_NAME
        value: seu_banco
      - key: SECRET_KEY
        value: sua_chave_secreta
