# Este é um Blueprint da Render. Ele define todos os serviços e bancos de dados do seu projeto.
# https://render.com/docs/infrastructure-as-code

services:
  # Define o Banco de Dados PostgreSQL
  # Este bloco garante que o banco de dados seja criado se não existir.
  - type: psql
    name: modelfleuriet-db
    region: oregon
    plan: free # Mude para um plano pago em produção, se necessário
    postgres:
      version: 16

  # Define o Serviço Web
  - type: web
    name: modelfleuriet
    region: oregon # CRÍTICO: Mesma região do banco de dados
    env: python
    plan: free # Mude para um plano pago em produção, se necessário
    
    # Filtro de build: só faz novo deploy se arquivos relevantes forem alterados
    buildFilter:
      paths:
      - "flask_app.py"
      - "core/**"
      - "templates/**"
      - "requirements.txt"
      
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn flask_app:app"
    
    # Variáveis de Ambiente: A forma moderna e segura
    envVars:
      # Injeta automaticamente a URL de conexão INTERNA do banco de dados.
      # Isso substitui a necessidade de DB_HOST, DB_USER, DB_PASSWORD, DB_NAME.
      - key: DATABASE_URL
        fromDatabase:
          name: modelfleuriet-db
          property: internalUrl
          
      # Deixa a Render gerar e gerenciar uma chave secreta segura para você.
      - key: SECRET_KEY
        generateValue: true
        
      - key: PYTHON_VERSION
        value: "3.10.13"
