# Arquivo: render.yaml
# Versão: FINAL - Para estrutura de projeto simplificada

services:
  - type: web
    name: modelfleuriet
    region: oregon
    plan: free
    env: python
    rootDir: .
    # Comando de build simplificado, pois todos os arquivos estão na raiz:
    buildCommand: "pip install -r requirements.txt && npm install && npm run build"
    # Comando para iniciar o servidor:
    startCommand: "gunicorn flask_app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: '3.10.13'
      - key: DATABASE_URL
        fromDatabase:
          name: modelfleuriet-db
          property: connectionString

databases:
  - name: modelfleuriet-db
    plan: free
